const Types = {
	ADD_PRODUCTS: 'ADD_PRODUCTS',
	//CART
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	CLEAR_CART: 'CLEAR_CART',
	//QUANTITY
	INCREASE_QUANTITY: 'INCREASE_QUANTITY',
	DECREASE_QUANTITY: 'DECREASE_QUANTITY',
	//STOCK
	ADD_STOCK: 'ADD_STOCK',
	SUBTRACT_STOCK: 'SUBTRACT_STOCK',
	RESTORE_STOCK: 'RESTORE_STOCK',
};

export default Types;
